import React from 'react';
import { BrandConfig } from '../types';
import { Mail, MapPin, Send, Sparkles, Lock, ShieldCheck, Edit3 } from 'lucide-react';
import { getButtonClasses, getButtonInlineStyle } from '../utils/themeStyles';
import { LogoBlock } from './LogoBlock';

interface FooterProps { brandData: BrandConfig; isAdminLoggedIn: boolean; onOpenLogin: () => void; onOpenCustomizer: (tab?: 'brand' | 'j1' | 'j2' | 'theme' | 'layouts' | 'labels' | 'security') => void; onOpenInquiry: () => void; }
export const Footer: React.FC<FooterProps> = ({ brandData, isAdminLoggedIn, onOpenLogin, onOpenCustomizer, onOpenInquiry }) => {
  const theme = brandData.theme;
  const secondaryBtnClass = getButtonClasses(theme, 'secondary', 'footer-workshop');
  const buttonInlineStyle = getButtonInlineStyle(theme, 'footer-workshop');
  const workshopText = theme?.workshopButtonText || 'Prendre Rendez-vous à l’Atelier';
  return <footer id="contact" className="bg-[#0e120f] text-[#e2d5c3] border-t border-[#2a352c] pt-16 pb-12 relative group/footer">
    {isAdminLoggedIn && <div className="absolute top-6 right-6 z-30 opacity-90 hover:opacity-100 transition-opacity"><button onClick={() => onOpenCustomizer('brand')} className="flex items-center space-x-1.5 bg-[#1b241d]/90 backdrop-blur-md border border-[#d4af37]/60 px-3 py-1.5 rounded-full shadow-2xl text-xs text-[#d4af37]"><Edit3 className="w-3 h-3" /><span>Éditer Contact</span></button></div>}
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-12 gap-10 pb-12 border-b border-[#222b24]">
        <div className="md:col-span-5 space-y-4"><LogoBlock brandData={brandData} kind="boutique" /><span className="text-[10px] uppercase tracking-widest text-[#d4af37] font-serif block">Édition Limitée des Pyrénées</span><p className="text-xs text-[#a3b1a5] leading-relaxed max-w-sm">{brandData.subtitle}</p><div className="pt-2 text-xs text-[#b8c5ba] space-y-2"><div className="flex items-center space-x-2"><MapPin className="w-4 h-4 text-[#d4af37]" /><span>Atelier : {brandData.designerLocation}</span></div><div className="flex items-center space-x-2"><Mail className="w-4 h-4 text-[#d4af37]" /><span>{brandData.contactEmail}</span></div></div></div>
        <div className="md:col-span-3 space-y-3"><h4 className="font-serif text-sm uppercase tracking-widest text-[#f3ece0] font-semibold">Collection & Esprit</h4><ul className="space-y-2 text-xs text-[#a3b1a5]"><li><a href="#comparatif" className="hover:text-[#d4af37]">Tableau Comparatif des Modèles</a></li><li><a href="#origines" className="hover:text-[#d4af37]">Histoire & Terroir Pyrénéen</a></li><li><a href="#lookbook" className="hover:text-[#d4af37]">Lookbook Editorial</a></li></ul></div>
        <div className="md:col-span-4 space-y-4"><h4 className="font-serif text-sm uppercase tracking-widest text-[#f3ece0] font-semibold">Restez Informé des Éditions</h4><p className="text-xs text-[#a3b1a5]">Recevez les invitations exclusives pour nos lancements et réassorts de laine vierge pyrénéenne.</p><form onSubmit={e => { e.preventDefault(); alert('Merci ! Vous êtes inscrit aux communications exclusives de la Maison des Pyrénées.'); }} className="flex space-x-2"><input type="email" required placeholder="votre.email@domaine.fr" className="flex-1 bg-[#1a221c] border border-[#313f33] text-xs text-white px-3 py-2.5 rounded-xl outline-none focus:border-[#d4af37]" /><button type="submit" className="px-4 py-2.5 bg-[#d4af37] text-[#121613] text-xs uppercase font-bold rounded-xl hover:brightness-110 flex items-center justify-center"><Send className="w-3.5 h-3.5" /></button></form><div className="pt-2"><button id="footer-workshop-btn" onClick={onOpenInquiry} style={buttonInlineStyle} className={`w-full py-3 px-4 text-xs uppercase tracking-wider font-semibold flex items-center justify-center space-x-2 ${secondaryBtnClass}`}><Sparkles className="w-3.5 h-3.5 text-[#d4af37]" /><span>{workshopText}</span></button></div></div>
      </div>
      <div className="pt-8 flex flex-col sm:flex-row items-center justify-between text-[11px] text-[#7a8a7c] space-y-4 sm:space-y-0"><div>© {new Date().getFullYear()} {brandData.brandName}. Fait avec passion dans les Pyrénées.</div><div className="flex items-center space-x-4 sm:space-x-6">{isAdminLoggedIn ? <button id="footer-admin-edit-btn" onClick={() => onOpenCustomizer('theme')} className="text-[#d4af37] hover:text-[#f3ece0] transition-colors flex items-center space-x-1.5 font-medium underline"><ShieldCheck className="w-3.5 h-3.5" /><span>Personnaliser le site</span></button> : <button id="footer-admin-login-btn" onClick={onOpenLogin} className="hover:text-[#d4af37] transition-colors flex items-center space-x-1 text-[#8f9f91]"><Lock className="w-3 h-3 text-[#b89f74]" /><span>Accès Espace Administrateur</span></button>}<span className="text-[#354337]">|</span><span>Design Champêtre Chic & Haute Montagne</span></div></div>
    </div>
  </footer>;
};
