// AUTO-GENERATED BY THE SITE VISUAL EDITOR.
// Do not edit manually: the next publication will overwrite this file.

export const publishedSiteContent = {
  "brandData": {
    "brandName": "MAISON Mailhag",
    "tagline": "Élégance Champêtre \u0026 Artisanat des Cimes 5",
    "subtitle": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
    "logoUrl": "/assets/pyrenees_brand_logo_1785338626936-BaITKbpK.jpg",
    "accentColor": "#4A5D4E",
    "foundingYear": "2025",
    "designerLocation": "Vallée de Lourdios \u0026 Pic du Midi",
    "heroBgImage": "/assets/pyrenees_landscape_hero_1785338591988-pbnVVBN-.jpg",
    "storyTitle": "Aux origines de la Maison",
    "storyText1": "Pensée entre pâturages verdoyants et sommets acérés, notre maison fait le pari d’un luxe brut et authentique. Chaque veste est façonnée pour affronter les brumes pyrénéennes tout en offrant une silhouette d’une distinction rare.",
    "storyText2": "Nous avons sélectionné des laines de bergers pyrénéens et des toiles techniques imperméables d’exception pour façonner ces deux pièces signatures : La Veste des Cimes et Le Manteau Pastorale.",
    "manifesto": [
      "Artisanat pyrénéen \u0026 matières naturelles nobles",
      "Conception durable, coupes millimétrées \u0026 résistance aux éléments",
      "Chic champêtre \u0026 raffinement intemporel"
    ],
    "contactEmail": "contact@maisondespyrenees.fr",
    "ordersEmail": "contact@maisondespyrenees.fr",
    "instagram": "@maison.des.pyrenees",
    "jackets": [
      {
        "id": "veste-des-cimes",
        "name": "La Veste des Cimes",
        "subTitle": "Modèle N°1 — Draps de Laine des Pyrénées \u0026 Coupe Structurée",
        "category": "Haute Montagne \u0026 Élégance",
        "price": 680,
        "currency": "€",
        "heroImage": "/assets/pyrenees_jacket_1_1785338603269-DB14hVWQ.jpg",
        "gallery": [
          "/assets/pyrenees_jacket_1_1785338603269-DB14hVWQ.jpg",
          "/assets/jacket_1_summit_1785338933118-BsWlKg9B.jpg",
          "/assets/wool_detail_macro_1785338963967-Dx13GKak.jpg",
          "/assets/pyrenees_landscape_hero_1785338591988-pbnVVBN-.jpg"
        ],
        "description": "Une veste à la stature majestueuse, tissée en drap de laine anthracite ultra-dense, conçue pour braver le vent des vallées tout en conservant une ligne affûtée.",
        "longDescription": "La Veste des Cimes incarne l’équilibre parfait entre la rigueur de la montagne et la finesse des tailleurs. Ses poches plaquées discrètes et sa doublure thermique en sergé fluide apportent aisance et protection contre le froid d’altitude.",
        "tagline": "Raffinement minéral \u0026 confort absolu",
        "fabrics": [
          "100% Pure Laine Vierge des Pyrénées",
          "Doublure Soie \u0026 Viscose",
          "Boutons en Corne Véritable"
        ],
        "colors": [
          {
            "name": "Gris Anthracite Cime",
            "hex": "#2C3035",
            "image": "/assets/pyrenees_jacket_1_1785338603269-DB14hVWQ.jpg"
          },
          {
            "name": "Vert Ardoise Pyrénéenne",
            "hex": "#3B4840"
          },
          {
            "name": "Brun Mousse",
            "hex": "#4A3E31"
          }
        ],
        "sizes": [
          "S",
          "M",
          "L",
          "XL",
          "XXL"
        ],
        "features": [
          {
            "iconName": "Shield",
            "title": "Coupe-Vent Naturel",
            "desc": "Drap de laine feutré à haute densité isolante."
          },
          {
            "iconName": "Feather",
            "title": "Douceur \u0026 Chaleur",
            "desc": "Toucher velouté sans irritation avec doublure respirante."
          },
          {
            "iconName": "Gem",
            "title": "Finition Tailleur",
            "desc": "Coutures gansées et finitions faites main en atelier."
          }
        ],
        "specs": {
          "weight": "1 100 g",
          "waterResistance": "Déperlant Naturel (Laine feutrée)",
          "warmthRating": "Indice 4/5 (Froid de montagne \u0026 intersaison)",
          "fitType": "Ajusté élégant",
          "origin": "Atelier Pyrénées Françaises",
          "care": "Nettoyage à sec spécialisé"
        },
        "hotspots": [
          {
            "id": "hs1-col",
            "x": 48,
            "y": 22,
            "title": "Col Officier à Revers",
            "description": "Protection thermique du cou rehaussée d’une bride en cuir pour fermer hermétiquement le col.",
            "category": "cut"
          },
          {
            "id": "hs1-boutons",
            "x": 52,
            "y": 45,
            "title": "Boutonnage en Corne Gravée",
            "description": "Chaque bouton est taillé dans la corne naturelle et gravé au laser avec le monogramme de la marque.",
            "category": "hardware"
          },
          {
            "id": "hs1-poche",
            "x": 62,
            "y": 65,
            "title": "Poches Soufflet d’Atelier",
            "description": "Grandes poches doublées en flanelle pour garder les mains au chaud lors des balades en altitude.",
            "category": "utility"
          }
        ]
      },
      {
        "id": "manteau-pastorale",
        "name": "Le Manteau Pastorale",
        "subTitle": "Modèle N°2 — Coton Waxé Champêtre \u0026 Doublure Tartan",
        "category": "Chic Champêtre \u0026 Tout Temps",
        "price": 590,
        "currency": "€",
        "heroImage": "/assets/pyrenees_jacket_2_1785338614694-C61ljqGO.jpg",
        "gallery": [
          "/assets/pyrenees_jacket_2_1785338614694-C61ljqGO.jpg",
          "/assets/jacket_2_pasture_1785338949621-BBl1ieKC.jpg",
          "/assets/waxed_detail_macro_1785338977808-Cpg_ucnu.jpg",
          "/assets/pyrenees_landscape_hero_1785338591988-pbnVVBN-.jpg"
        ],
        "description": "L’esprit champêtre pyrénéen réinventé : une veste robuste en coton huilé olive champêtre, agrémentée de détails en cuir patiné et boutons pression en laiton vieilli.",
        "longDescription": "Inspirée des habits traditionnels des gardiens de troupeaux et des randonneurs des sommets, cette veste conjugue imperméabilité totale et silhouette d’une classe incontestable pour la ville comme pour la campagne.",
        "tagline": "L’authenticité du terroir \u0026 la patine du temps",
        "fabrics": [
          "Coton Bio Huilé à la Cire d’Abeille",
          "Col en Velours Côtelé Marron",
          "Doublure Tartan Coton"
        ],
        "colors": [
          {
            "name": "Vert Olive Champêtre",
            "hex": "#44513E",
            "image": "/assets/pyrenees_jacket_2_1785338614694-C61ljqGO.jpg"
          },
          {
            "name": "Ocre Terre Brûlée",
            "hex": "#7A4D2E"
          },
          {
            "name": "Noir Écorce",
            "hex": "#222222"
          }
        ],
        "sizes": [
          "S",
          "M",
          "L",
          "XL",
          "XXL"
        ],
        "features": [
          {
            "iconName": "CloudRain",
            "title": "100% Imperméable",
            "desc": "Cire végétale d’abeille hydrofuge appliquée artisanalement."
          },
          {
            "iconName": "Compass",
            "title": "Poches Multi-Usage",
            "desc": "3 poches intérieures zippées \u0026 poches repose-mains en microfleece."
          },
          {
            "iconName": "Sparkles",
            "title": "Patine Unique",
            "desc": "Le tissu s’embellit au fil du temps et de vos escapades."
          }
        ],
        "specs": {
          "weight": "1 250 g",
          "waterResistance": "10 000 mm (Cire imperméabilisante)",
          "warmthRating": "Indice 3/5 (Polyvalente 4 Saisons)",
          "fitType": "Droit chic avec cordon de cintrage intérieur",
          "origin": "Atelier Pyrénées Françaises",
          "care": "Re-cirage annuel au baume naturel"
        },
        "hotspots": [
          {
            "id": "hs2-col",
            "x": 46,
            "y": 20,
            "title": "Col Velours Doux",
            "description": "Toucher velours côtelé marron qui évite tout frottement et garde la chaleur du cou.",
            "category": "fabric"
          },
          {
            "id": "hs2-fermeture",
            "x": 50,
            "y": 42,
            "title": "Zip Double Curseur \u0026 Rabat Laiton",
            "description": "Double zip YKK pour ajuster l’ouverture en position assise ou à cheval.",
            "category": "hardware"
          },
          {
            "id": "hs2-cuir",
            "x": 35,
            "y": 58,
            "title": "Renforts Coudes en Cuir Cognac",
            "description": "Empiècements en cuir de veau pleine fleur pour une durabilité inégalée.",
            "category": "utility"
          }
        ]
      },
      {
        "id": "veste-modele-9583",
        "name": "Veste Modèle 3",
        "subTitle": "Création Artisanale Pyrénéenne",
        "category": "Haute Montagne",
        "price": 120,
        "currency": "€",
        "heroImage": "/src/assets/images/veste-cimes.png",
        "gallery": [
          "/src/assets/images/veste-cimes.png",
          "/src/assets/images/manteau-pastorale.png",
          "/src/assets/images/hero-montagne.png"
        ],
        "description": "Pièce authentique confectionnée dans notre atelier avec les plus nobles laines des vallées pyrénéennes.",
        "longDescription": "Chaque pièce est coupée à la main et assemblée avec une attention méticuleuse portée aux finitions, boutons en corne et doublure respirante.",
        "tagline": "L’alliance de la chaleur brute et du raffinement intemporel.",
        "fabrics": [
          "100% Drap de Laine Vierge des Pyrénées",
          "Doublure Cupro Respirante",
          "Boutons en Corne Véritable"
        ],
        "colors": [
          {
            "name": "Kaki Haute Forêt",
            "hex": "#445138"
          },
          {
            "name": "Anthracite Minéral",
            "hex": "#26292b"
          },
          {
            "name": "Bronze Pyrénéen",
            "hex": "#635336"
          }
        ],
        "sizes": [
          "Taille unique"
        ],
        "features": [
          {
            "iconName": "Feather",
            "title": "Chaleur Naturelle",
            "desc": "Protection thermique optimale jusqu’à -15°C."
          },
          {
            "iconName": "CloudRain",
            "title": "Déperlance Naturelle",
            "desc": "La lanoline préserve l’imperméabilité des fibres."
          },
          {
            "iconName": "Shield",
            "title": "Confection Garantie à Vie",
            "desc": "Réparation et entretien assurés par notre atelier."
          }
        ],
        "specs": {
          "weight": "1 250 g",
          "waterResistance": "Déperlant naturel",
          "warmthRating": "Idéal -10°C à +12°C",
          "fitType": "Coupe Droite Ajustée",
          "origin": "Atelier de Cauterets (Hautes-Pyrénées, France)",
          "care": "Nettoyage à sec uniquement"
        },
        "hotspots": [
          {
            "id": "h1",
            "title": "Col Montant Doublé",
            "description": "Empêche les infiltrations d’air glacé en altitude.",
            "x": 50,
            "y": 18,
            "category": "cut"
          },
          {
            "id": "h2",
            "title": "Poches Poitrines Passepoilées",
            "description": "Taillées pour accueillir gants et carnet d’alpiniste.",
            "x": 42,
            "y": 38,
            "category": "utility"
          },
          {
            "id": "h3",
            "title": "Drap de Laine Brut Feutré",
            "description": "Tissage dense résistant aux ronces et à l’usure des cimes.",
            "x": 60,
            "y": 65,
            "category": "fabric"
          }
        ]
      },
      {
        "id": "veste-modele-0901",
        "name": "Veste Modèle 4",
        "subTitle": "Création Artisanale Pyrénéenne",
        "category": "Haute Montagne",
        "price": 890,
        "currency": "€",
        "heroImage": "/src/assets/images/veste-cimes.png",
        "gallery": [
          "/src/assets/images/veste-cimes.png",
          "/src/assets/images/manteau-pastorale.png",
          "/src/assets/images/hero-montagne.png"
        ],
        "description": "Pièce authentique confectionnée dans notre atelier avec les plus nobles laines des vallées pyrénéennes.",
        "longDescription": "Chaque pièce est coupée à la main et assemblée avec une attention méticuleuse portée aux finitions, boutons en corne et doublure respirante.",
        "tagline": "L’alliance de la chaleur brute et du raffinement intemporel.",
        "fabrics": [
          "100% Drap de Laine Vierge des Pyrénées",
          "Doublure Cupro Respirante",
          "Boutons en Corne Véritable"
        ],
        "colors": [
          {
            "name": "Kaki Haute Forêt",
            "hex": "#445138"
          },
          {
            "name": "Anthracite Minéral",
            "hex": "#26292b"
          },
          {
            "name": "Bronze Pyrénéen",
            "hex": "#635336"
          }
        ],
        "sizes": [
          "XS",
          "S",
          "M",
          "L",
          "XL",
          "XXL",
          "Sur Mesure"
        ],
        "features": [
          {
            "iconName": "Feather",
            "title": "Chaleur Naturelle",
            "desc": "Protection thermique optimale jusqu’à -15°C."
          },
          {
            "iconName": "CloudRain",
            "title": "Déperlance Naturelle",
            "desc": "La lanoline préserve l’imperméabilité des fibres."
          },
          {
            "iconName": "Shield",
            "title": "Confection Garantie à Vie",
            "desc": "Réparation et entretien assurés par notre atelier."
          }
        ],
        "specs": {
          "weight": "1 250 g",
          "waterResistance": "Déperlant naturel",
          "warmthRating": "Idéal -10°C à +12°C",
          "fitType": "Coupe Droite Ajustée",
          "origin": "Atelier de Cauterets (Hautes-Pyrénées, France)",
          "care": "Nettoyage à sec uniquement"
        },
        "hotspots": [
          {
            "id": "h1",
            "title": "Col Montant Doublé",
            "description": "Empêche les infiltrations d’air glacé en altitude.",
            "x": 50,
            "y": 18,
            "category": "cut"
          },
          {
            "id": "h2",
            "title": "Poches Poitrines Passepoilées",
            "description": "Taillées pour accueillir gants et carnet d’alpiniste.",
            "x": 42,
            "y": 38,
            "category": "utility"
          },
          {
            "id": "h3",
            "title": "Drap de Laine Brut Feutré",
            "description": "Tissage dense résistant aux ronces et à l’usure des cimes.",
            "x": 60,
            "y": 65,
            "category": "fabric"
          }
        ]
      },
      {
        "id": "veste-modele-8681",
        "name": "Veste Modèle 5",
        "subTitle": "Création Artisanale Pyrénéenne",
        "category": "Haute Montagne",
        "price": 890,
        "currency": "€",
        "heroImage": "/src/assets/images/veste-cimes.png",
        "gallery": [
          "/src/assets/images/veste-cimes.png",
          "/src/assets/images/manteau-pastorale.png",
          "/src/assets/images/hero-montagne.png"
        ],
        "description": "Pièce authentique confectionnée dans notre atelier avec les plus nobles laines des vallées pyrénéennes.",
        "longDescription": "Chaque pièce est coupée à la main et assemblée avec une attention méticuleuse portée aux finitions, boutons en corne et doublure respirante.",
        "tagline": "L’alliance de la chaleur brute et du raffinement intemporel.",
        "fabrics": [
          "100% Drap de Laine Vierge des Pyrénées",
          "Doublure Cupro Respirante",
          "Boutons en Corne Véritable"
        ],
        "colors": [
          {
            "name": "Kaki Haute Forêt",
            "hex": "#445138"
          },
          {
            "name": "Anthracite Minéral",
            "hex": "#26292b"
          },
          {
            "name": "Bronze Pyrénéen",
            "hex": "#635336"
          }
        ],
        "sizes": [
          "XS",
          "S",
          "M",
          "L",
          "XL",
          "XXL",
          "Sur Mesure"
        ],
        "features": [
          {
            "iconName": "Feather",
            "title": "Chaleur Naturelle",
            "desc": "Protection thermique optimale jusqu’à -15°C."
          },
          {
            "iconName": "CloudRain",
            "title": "Déperlance Naturelle",
            "desc": "La lanoline préserve l’imperméabilité des fibres."
          },
          {
            "iconName": "Shield",
            "title": "Confection Garantie à Vie",
            "desc": "Réparation et entretien assurés par notre atelier."
          }
        ],
        "specs": {
          "weight": "1 250 g",
          "waterResistance": "Déperlant naturel",
          "warmthRating": "Idéal -10°C à +12°C",
          "fitType": "Coupe Droite Ajustée",
          "origin": "Atelier de Cauterets (Hautes-Pyrénées, France)",
          "care": "Nettoyage à sec uniquement"
        },
        "hotspots": [
          {
            "id": "h1",
            "title": "Col Montant Doublé",
            "description": "Empêche les infiltrations d’air glacé en altitude.",
            "x": 50,
            "y": 18,
            "category": "cut"
          },
          {
            "id": "h2",
            "title": "Poches Poitrines Passepoilées",
            "description": "Taillées pour accueillir gants et carnet d’alpiniste.",
            "x": 42,
            "y": 38,
            "category": "utility"
          },
          {
            "id": "h3",
            "title": "Drap de Laine Brut Feutré",
            "description": "Tissage dense résistant aux ronces et à l’usure des cimes.",
            "x": 60,
            "y": 65,
            "category": "fabric"
          }
        ]
      }
    ],
    "theme": {
      "buttonStyle": "gold-laiton",
      "buttonRadius": "rounded-full",
      "buttonSize": "standard",
      "buttonBackgroundImageUrl": "",
      "buttonBackgroundOverlay": 28,
      "buttonOverrides": {
        "navbar-order": {
          "buttonStyle": "brut-montagne",
          "buttonSize": "compact",
          "buttonRadius": "rounded-full",
          "backgroundImageUrl": "",
          "backgroundOverlay": 41,
          "buttonTextSize": "small",
          "buttonTextColor": ""
        },
        "hero-discover": {
          "buttonSize": "standard",
          "buttonStyle": "gold-laiton",
          "backgroundOverlay": 26,
          "buttonRadius": "rounded-none"
        },
        "hero-order": {
          "buttonStyle": "gold-laiton",
          "backgroundImageUrl": "/assets/persistent-media-1.png"
        },
        "showcase-order": {
          "buttonStyle": "gold-laiton"
        },
        "lookbook-order": {
          "buttonStyle": "gold-laiton",
          "buttonTextColor": ""
        },
        "comparison-order": {
          "buttonStyle": "gold-laiton"
        },
        "footer-workshop": {
          "buttonStyle": "sapin-cimes"
        }
      },
      "cardStyle": "atelier-relief",
      "heroLayout": "split-cards",
      "showcaseLayout": "split-interactive",
      "sectionOrder": [
        "hero",
        "collection",
        "comparatif",
        "lookbook",
        "origines",
        "contact"
      ],
      "hiddenSections": [],
      "textAlign": "center",
      "buttonAlign": "center",
      "heroBadgePosition": "top",
      "cardMediaPosition": "left",
      "contentPadding": "comfortable",
      "containerWidth": "standard",
      "productBlocksOrder": [
        "title-price",
        "description",
        "colors",
        "sizes",
        "specs",
        "cta"
      ],
      "formFieldsOrder": [
        "name",
        "email",
        "phone",
        "jacket",
        "color",
        "size",
        "requestType",
        "message"
      ],
      "orderButtonText": "Commander",
      "discoverButtonText": "Découvrir",
      "inquiryButtonText": "Commander sur Mesure",
      "workshopButtonText": "Prendre Rendez-vous à l'Atelier",
      "heroBadgeText": "Édition Limitée des Pyrénées",
      "heroTitlePrefix": "Thème Champêtre \u0026 Élégance",
      "comparisonCriteria": [
        {
          "id": "crit_category",
          "label": "Style principal",
          "key": "category"
        },
        {
          "id": "crit_fabric",
          "label": "Tissu signature",
          "key": "fabric"
        },
        {
          "id": "crit_warmth",
          "label": "Indice de Chaleur",
          "key": "warmth"
        },
        {
          "id": "crit_water",
          "label": "Résistance à la pluie",
          "key": "water"
        },
        {
          "id": "crit_weight",
          "label": "Poids de la veste",
          "key": "weight"
        },
        {
          "id": "crit_fit",
          "label": "Coupe \u0026 Silhouette",
          "key": "fit"
        },
        {
          "id": "crit_care",
          "label": "Entretien",
          "key": "care"
        }
      ],
      "collectionTabLabel": "Les Articles",
      "navOrder": [
        "collection",
        "comparatif",
        "lookbook",
        "origines",
        "contact"
      ],
      "comparatifTabLabel": "Tableau Comparatif des Articles",
      "lookbookTabLabel": "Bibliothèque"
    },
    "logos": {
      "boutique": {
        "imageUrl": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787218936185-admin-sheep.png",
        "text": "MAISON MAILHA",
        "secondaryText": "ÉDITION LIMITÉE DES PYRÉNÉES 4",
        "fontFamily": "serif",
        "textColor": "#f3ece0",
        "textSize": "21px",
        "imageSize": 58,
        "gap": 12,
        "showText": true
      },
      "gite": {
        "imageUrl": "/assets/persistent-media-2.png",
        "text": "GÎTE DES\nPYR",
        "secondaryText": "Test 4",
        "fontFamily": "sans",
        "textColor": "#f3ece0",
        "textSize": "20px",
        "imageSize": 58,
        "gap": 12,
        "showText": true
      }
    }
  },
  "editorConfig": {
    "adminBarPosition": "bottom",
    "floatingImages": [
      {
        "id": "floating-1787160893741-7a0i8v",
        "section": "hero",
        "url": "/assets/persistent-media-2.png",
        "alt": "",
        "x": 15,
        "y": 23,
        "size": 104,
        "rotate": -18,
        "opacity": 100,
        "animation": "float",
        "mobile": true,
        "visible": true
      }
    ],
    "schemaVersion": 5,
    "blocks": [
      {
        "id": "block-1787003030958",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 55,
        "text": "Nouveau textetest",
        "visible": true,
        "kind": "text"
      },
      {
        "id": "element-bgfo10",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Nouveau texte",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e div.fixed.z-\\[25\\]:nth-of-type(2) \u003e div.px-3.py-2",
        "kind": "text",
        "fontFamily": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
        "fontSize": "16px",
        "color": "#f3ece0"
      },
      {
        "id": "element-2j3eoa",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Édition Limitée des Pyrénées",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.flex.justify-center:nth-of-type(1) \u003e div.inline-flex.items-center \u003e span.text-\\[\\#e2d5c3\\]:nth-of-type(3)",
        "kind": "text",
        "fontFamily": "ui-serif, Georgia, Cambria, \"Times New Roman\", Times, serif",
        "fontSize": "12px",
        "color": "#f0f0f0"
      },
      {
        "id": "element-7hx1tr",
        "type": "heading",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Thème Champêtre \u0026 Élégance  \nMAISON Mailha",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.text-center.max-w-4xl:nth-of-type(2) \u003e h1.font-serif.text-4xl",
        "kind": "text",
        "fontFamily": "Playfair Display, Georgia, serif",
        "fontSize": "64px",
        "color": "#a98334"
      },
      {
        "id": "element-1yp1kl6",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-role=\"hero-line-2\"]",
        "kind": "text",
        "text": "MAISON MAILHAG",
        "fontFamily": "ui-serif",
        "fontSize": "72px",
        "color": "rgb(245, 238, 223)"
      },
      {
        "id": "element-y3kce5",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(1) \u003e h3:nth-of-type(1)",
        "kind": "text",
        "text": "MAISON MAILHA",
        "fontFamily": "ui-serif",
        "fontSize": "20px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-7bccga",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "section:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "kind": "media",
        "text": "",
        "url": "https://site-internet-beno-t.vercel.app/assets/pyrenees_jacket_1_1785338603269-DB14hVWQ.jpg"
      },
      {
        "id": "element-1pm4g7c",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(1)",
        "kind": "text",
        "text": "3. Tableau Comparatif",
        "fontFamily": "ui-serif",
        "fontSize": "12px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-1f5ergz",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(3) \u003e section:nth-of-type(1) \u003e div:nth-of-type(2) \u003e div:nth-of-type(1) \u003e h2:nth-of-type(1)",
        "kind": "text",
        "text": "Tableau des articles",
        "fontFamily": "ui-serif",
        "fontSize": "48px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-1l9gpen",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(2) \u003e section:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "kind": "media",
        "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787063558934-20260605_205859.jpg"
      },
      {
        "id": "element-115krkx",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-hero-line=\"2\"]",
        "kind": "text",
        "text": "MAISON Mailhag",
        "fontFamily": "ui-serif",
        "fontSize": "72px",
        "color": "rgb(245, 238, 223)",
        "locator": {
          "tag": "span",
          "text": "MAISON Mailhag 4",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "element-1vd5k7f",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "button:nth-of-type(3) \u003e img:nth-of-type(1)",
        "kind": "media",
        "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787063825877-20260605_205836.jpg"
      },
      {
        "id": "element-ramuve",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-role=\"jacket-veste-des-cimes-gallery-2\"]",
        "kind": "media",
        "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787063825877-20260605_205836.jpg"
      },
      {
        "id": "element-12mgdm6",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "kind": "media",
        "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787063825877-20260605_205836.jpg"
      },
      {
        "id": "element-8l43pq",
        "type": "image",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-role=\"jacket-veste-modele-9583-gallery-0\"]",
        "kind": "media",
        "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787063825877-20260605_205836.jpg"
      },
      {
        "id": "element-1dd70g4",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "button:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(2)",
        "kind": "text",
        "text": "Édition Limitée des Pyrénées",
        "fontFamily": "-apple-system",
        "fontSize": "10px",
        "color": "#d2b16f"
      },
      {
        "id": "element-1oie024",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "kind": "text",
        "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
        "fontFamily": "-apple-system",
        "fontSize": "16px",
        "color": "rgb(163, 176, 162)",
        "locator": {
          "tag": "p",
          "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 4.",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "element-1ju1s8k",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-hero-line=\"1\"]",
        "kind": "text",
        "text": "Thème Champêtre \u0026 Élégance",
        "fontFamily": "ui-serif",
        "fontSize": "60px",
        "color": "rgb(194, 162, 109)",
        "locator": {
          "tag": "span",
          "text": "Thème Champêtre \u0026 Élégance 4",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "hero-tagline",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "p",
          "text": "\"Élégance Champêtre \u0026 Artisanat des Cimes 5\"",
          "sectionId": "hero",
          "occurrence": 0
        },
        "kind": "text",
        "text": "\"Élégance Champêtre \u0026 Artisanat des Cimes\"",
        "fontFamily": "ui-serif",
        "fontSize": "24px",
        "color": "rgb(208, 197, 180)"
      },
      {
        "id": "hero-subtitle",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "p",
          "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
          "sectionId": "hero",
          "occurrence": 0
        },
        "kind": "text",
        "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture.",
        "fontFamily": "-apple-system",
        "fontSize": "16px",
        "color": "rgb(163, 176, 162)"
      }
    ],
    "editorElements": {
      "block-1787003030958": {
        "id": "block-1787003030958",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "element-bgfo10": {
        "id": "element-bgfo10",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e div.fixed.z-\\[25\\]:nth-of-type(2) \u003e div.px-3.py-2",
        "locator": "data-vce-id"
      },
      "element-2j3eoa": {
        "id": "element-2j3eoa",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.flex.justify-center:nth-of-type(1) \u003e div.inline-flex.items-center \u003e span.text-\\[\\#e2d5c3\\]:nth-of-type(3)",
        "locator": "data-vce-id"
      },
      "element-7hx1tr": {
        "id": "element-7hx1tr",
        "type": "heading",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.text-center.max-w-4xl:nth-of-type(2) \u003e h1.font-serif.text-4xl",
        "locator": "data-vce-id"
      },
      "element-1yp1kl6": {
        "id": "element-1yp1kl6",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-role=\"hero-line-2\"]",
        "locator": "data-vce-id"
      },
      "element-y3kce5": {
        "id": "element-y3kce5",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(1) \u003e h3:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-7bccga": {
        "id": "element-7bccga",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "section:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-1pm4g7c": {
        "id": "element-1pm4g7c",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-1f5ergz": {
        "id": "element-1f5ergz",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(3) \u003e section:nth-of-type(1) \u003e div:nth-of-type(2) \u003e div:nth-of-type(1) \u003e h2:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-1l9gpen": {
        "id": "element-1l9gpen",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "div:nth-of-type(2) \u003e section:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-115krkx": {
        "id": "element-115krkx",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-hero-line=\"2\"]",
        "locator": "data-vce-id"
      },
      "element-1vd5k7f": {
        "id": "element-1vd5k7f",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "button:nth-of-type(3) \u003e img:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-ramuve": {
        "id": "element-ramuve",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "[data-vce-role=\"jacket-veste-des-cimes-gallery-2\"]",
        "locator": "data-vce-id"
      },
      "element-12mgdm6": {
        "id": "element-12mgdm6",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "div:nth-of-type(3) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e img:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-8l43pq": {
        "id": "element-8l43pq",
        "type": "image",
        "kind": "media",
        "section": "hero",
        "selector": "[data-vce-role=\"jacket-veste-modele-9583-gallery-0\"]",
        "locator": "data-vce-id"
      },
      "element-1dd70g4": {
        "id": "element-1dd70g4",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "button:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(2)",
        "locator": "data-vce-id"
      },
      "element-1oie024": {
        "id": "element-1oie024",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "element-1ju1s8k": {
        "id": "element-1ju1s8k",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-hero-line=\"1\"]",
        "locator": "data-vce-id"
      },
      "hero-tagline": {
        "id": "hero-tagline",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "hero-subtitle": {
        "id": "hero-subtitle",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      }
    }
  },
  "publishedAt": 1787238329686
} as const;
