// AUTO-GENERATED BY THE SITE VISUAL EDITOR.
// This initial file is intentionally empty.
// After the first successful publication, /api/site-publish.ts replaces it.

export const publishedSiteContent = {
  brandData: null,
  editorConfig: null,
} as const;
