// AUTO-GENERATED BY THE SITE VISUAL EDITOR.
// Do not edit manually: the next publication will overwrite this file.

export const publishedSiteContent = {
  "brandData": {
    "brandName": "Thème Champêtre \u0026 Élégance",
    "tagline": "Élégance Champêtre \u0026 Artisanat des Cimes 5",
    "subtitle": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
    "logoUrl": "/assets/pyrenees_brand_logo_1785338626936-BaITKbpK.jpg",
    "accentColor": "#4A5D4E",
    "foundingYear": "2025",
    "designerLocation": "Vallée de Lourdios \u0026 Pic du Midi",
    "heroBgImage": "",
    "storyTitle": "Aux origines de la Maison",
    "storyText1": "Pensée entre pâturages verdoyants et sommets acérés, notre maison fait le pari d’un luxe brut et authentique. Chaque veste est façonnée pour affronter les brumes pyrénéennes tout en offrant une silhouette d’une distinction rare.",
    "storyText2": "Nous avons sélectionné des laines de bergers pyrénéens et des toiles techniques imperméables d’exception pour façonner ces deux pièces signatures : La Veste des Cimes et Le Manteau Pastorale.",
    "manifesto": [
      "Artisanat pyrénéen \u0026 matières naturelles nobles",
      "Conception durable, coupes millimétrées \u0026 résistance aux éléments",
      "Chic champêtre \u0026 raffinement intemporel"
    ],
    "contactEmail": "contact@maisondespyrenees.fr",
    "ordersEmail": "contact@maisondespyrenees.fr",
    "instagram": "@maison.des.pyrenees",
    "gite": {
      "name": "Le Gîte",
      "location": "Pyrénées",
      "tagline": "",
      "heroImage": "",
      "intro": {
        "title": "",
        "text": ""
      },
      "gallery": [],
      "videoUrl": "",
      "videoPoster": "",
      "essentials": [],
      "bookingText": "",
      "airbnbUrl": "",
      "bookingUrl": "",
      "nearby": [],
      "access": {
        "title": "",
        "text": ""
      },
      "modules": [
        {
          "id": "gite-accueil",
          "label": "Accueil",
          "visible": true,
          "width": 100,
          "height": 940,
          "background": {
            "type": "image",
            "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787318006397-dino-reichmuth-zlV1Ksvifvs-unsplash.webp",
            "overlay": 25
          }
        },
        {
          "id": "gite-le-gite",
          "label": "Le gîte",
          "visible": true,
          "width": 100,
          "height": 690
        },
        {
          "id": "gite-sejourner",
          "label": "Séjourner",
          "visible": true,
          "width": 100,
          "height": 520
        },
        {
          "id": "gite-region",
          "label": "La région",
          "visible": true,
          "width": 100,
          "height": 520
        },
        {
          "id": "gite-acces",
          "label": "Accès",
          "visible": true,
          "width": 100,
          "height": 520
        }
      ],
      "navLabels": {
        "gite-accueil": "Accueil",
        "gite-le-gite": "Le gîte",
        "gite-region": "La région",
        "gite-sejourner": "Séjourner",
        "gite-acces": "Accès"
      },
      "navOrder": [
        "gite-accueil",
        "gite-le-gite",
        "gite-sejourner",
        "gite-region",
        "gite-acces"
      ],
      "navCta": {
        "label": "Réserver",
        "link": "",
        "visible": false
      },
      "navAdminLabel": "⌂",
      "contentBlocks": [
        {
          "id": "gite-block-1787303077623-485fcy",
          "moduleId": "gite-accueil",
          "type": "text",
          "x": 11.927083333333334,
          "y": 71.875,
          "width": 30,
          "height": 18,
          "text": "Le Gîte",
          "link": "",
          "url": "",
          "fontSize": 70,
          "color": "#ffffff",
          "align": "left",
          "fontFamily": "display",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "transparent",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "autoSize": true
        },
        {
          "id": "gite-block-1787318829980-hhzoaf",
          "moduleId": "gite-accueil",
          "type": "text",
          "x": 8.59375,
          "y": 70.125,
          "width": 30,
          "height": 18,
          "text": "Pyrénées",
          "link": "",
          "url": "",
          "fontSize": 18,
          "color": "#ffffff",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "transparent",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "autoSize": true
        },
        {
          "id": "gite-block-1787304469172-08tmq3",
          "moduleId": "gite-le-gite",
          "type": "video",
          "x": 48,
          "y": 31,
          "width": 48,
          "height": 57,
          "text": "Nouvelle zone de texte",
          "link": "",
          "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/section-background-1787319176828-test-qFiRi6B7U2jVKy4bZbGRU23ATb7Fzk.mp4",
          "fontSize": 18,
          "color": "#24231f",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "rgba(255,255,255,0.88)",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "autoSize": false
        },
        {
          "id": "gite-block-1787318886775-1k9pkt",
          "moduleId": "gite-accueil",
          "type": "text",
          "x": 15.625,
          "y": 83.40425531914893,
          "width": 30,
          "height": 18,
          "text": "Une parenthèse au cœur des montagnes.",
          "link": "",
          "url": "",
          "fontSize": 18,
          "color": "#ffffff",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "transparent",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "autoSize": true
        },
        {
          "id": "gite-block-1787304121004-b1n56m",
          "moduleId": "gite-accueil",
          "type": "button",
          "x": 10.208333333333334,
          "y": 85.1063829787234,
          "width": 9,
          "height": 11,
          "text": "",
          "link": "https://www.airbnb.fr/?c=.pi0.pk90572135_4063331735\u0026gclsrc=aw.ds\u0026\u0026c=.pi0.pk90572135_4063331735\u0026localized_ghost=true\u0026gad_source=1\u0026gad_campaignid=90572135\u0026gclid=CjwKCAjw7p_UBhBlEiwAhpIs77A2PVrzzeYuiMgDKx-Njkje5b79dNA8vM4-4zdnb1Q9nFPqxkx0MhoC_70QAvD_BwE",
          "url": "",
          "fontSize": 18,
          "color": "#24231f",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "transparent",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "buttonImageUrl": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787308430125-AirBnb.png",
          "buttonImageEnabled": true
        },
        {
          "id": "gite-block-1787318968407-5kw0gh",
          "moduleId": "gite-accueil",
          "type": "button",
          "x": 21,
          "y": 85,
          "width": 8,
          "height": 11,
          "text": "Réserver",
          "link": "",
          "url": "",
          "fontSize": 18,
          "color": "#24231f",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "transparent",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "cover",
          "visible": true,
          "buttonImageUrl": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787319038241-Booking.png",
          "buttonImageEnabled": true,
          "autoSize": false
        },
        {
          "id": "gite-block-1787319271954-mxrw2w",
          "moduleId": "gite-sejourner",
          "type": "image",
          "x": 29.114583333333332,
          "y": 85.76923076923076,
          "width": 32,
          "text": "Nouvelle zone de texte",
          "link": "",
          "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787319288178-andrea-davis-nbI8gqbBaHo-unsplash.webp",
          "fontSize": 18,
          "color": "#24231f",
          "align": "left",
          "fontFamily": "sans",
          "fontWeight": 400,
          "lineHeight": 1.45,
          "italic": false,
          "backgroundColor": "rgba(255,255,255,0.88)",
          "borderColor": "#8c6e3f",
          "borderWidth": 0,
          "borderRadius": 18,
          "padding": 12,
          "opacity": 100,
          "rotation": 0,
          "objectFit": "contain",
          "visible": true
        }
      ],
      "navBackgroundColor": "#000000",
      "navOpacity": 10
    },
    "jackets": [
      {
        "id": "veste-des-cimes",
        "name": "La Veste des Cimes",
        "subTitle": "Modèle N°1 — Draps de Laine des Pyrénées \u0026 Coupe Structurée",
        "category": "Haute Montagne \u0026 Élégance",
        "price": 110,
        "currency": "€",
        "heroImage": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787255862341-Image-1.jpg",
        "gallery": [
          "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787255862341-Image-1.jpg",
          "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787255871534-Image-2.jpg"
        ],
        "description": "Une veste à la stature majestueuse, tissée en drap de laine anthracite ultra-dense, conçue pour braver le vent des vallées tout en conservant une ligne affûtée.",
        "longDescription": "La Veste des Cimes incarne l’équilibre parfait entre la rigueur de la montagne et la finesse des tailleurs. Ses poches plaquées discrètes et sa doublure thermique en sergé fluide apportent aisance et protection contre le froid d’altitude.",
        "tagline": "Raffinement minéral \u0026 confort absolu",
        "fabrics": [
          "100% Pure Laine Vierge des Pyrénées",
          "Doublure Soie \u0026 Viscose",
          "Boutons en Corne Véritable"
        ],
        "colors": [
          {
            "name": "Gris Anthracite Cime",
            "hex": "#2C3035",
            "image": "/assets/pyrenees_jacket_1_1785338603269-DB14hVWQ.jpg"
          },
          {
            "name": "Vert Ardoise Pyrénéenne",
            "hex": "#3B4840"
          },
          {
            "name": "Brun Mousse",
            "hex": "#4A3E31"
          }
        ],
        "sizes": [
          "S",
          "M",
          "L",
          "XL",
          "XXL"
        ],
        "features": [
          {
            "iconName": "Shield",
            "title": "Coupe-Vent Naturel",
            "desc": "Drap de laine feutré à haute densité isolante."
          },
          {
            "iconName": "Feather",
            "title": "Douceur \u0026 Chaleur",
            "desc": "Toucher velouté sans irritation avec doublure respirante."
          },
          {
            "iconName": "Gem",
            "title": "Finition Tailleur",
            "desc": "Coutures gansées et finitions faites main en atelier."
          }
        ],
        "specs": {
          "weight": "1 100 g",
          "waterResistance": "Déperlant Naturel (Laine feutrée)",
          "warmthRating": "Indice 4/5 (Froid de montagne \u0026 intersaison)",
          "fitType": "Ajusté élégant",
          "origin": "Atelier Pyrénées Françaises",
          "care": "Nettoyage à sec spécialisé"
        },
        "hotspots": [
          {
            "id": "hs1-col",
            "x": 59,
            "y": 3,
            "title": "Col Officier à Revers",
            "description": "Protection thermique du cou rehaussée d’une bride en cuir pour fermer hermétiquement le col.",
            "category": "cut"
          },
          {
            "id": "hs1-boutons",
            "x": 45,
            "y": 56,
            "title": "Boutonnage en Corne Gravée",
            "description": "Chaque bouton est taillé dans la corne naturelle et gravé au laser avec le monogramme de la marque.",
            "category": "hardware"
          },
          {
            "id": "hs1-poche",
            "x": 59,
            "y": 76,
            "title": "Poches Soufflet d’Atelier",
            "description": "Grandes poches doublées en flanelle pour garder les mains au chaud lors des balades en altitude.",
            "category": "utility"
          }
        ],
        "isAvailable": true,
        "availabilityStatus": "on-sale",
        "customSpecs": {}
      },
      {
        "name": "Veste des Cîmes Enfant",
        "subTitle": "Confection Artisanale des Pyrénées",
        "category": "Femme \u0026 Enfant",
        "price": 60,
        "currency": "€",
        "heroImage": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787255936718-Image-3.jpg",
        "gallery": [
          "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787255936718-Image-3.jpg"
        ],
        "description": "Veste artisanale d'exception tissée dans les Pyrénées.",
        "longDescription": "Fabriquée selon des savoir-faire d'autrefois en pure laine sélectionnée.",
        "tagline": "L'élégance des cimes",
        "fabrics": [
          "Laine des Pyrénées 100% naturelle"
        ],
        "colors": [
          {
            "name": "Gris Aspe",
            "hex": "#4a524b"
          },
          {
            "name": "Ocre Vignemale",
            "hex": "#8c6b43"
          },
          {
            "name": "Vert des cîmes",
            "hex": "#526355"
          }
        ],
        "sizes": [
          "8",
          "10",
          "12",
          "14",
          "XS",
          "S"
        ],
        "isAvailable": true,
        "features": [
          {
            "iconName": "Shield",
            "title": "Coupe-Vent",
            "desc": "Protection thermique haute montagne"
          }
        ],
        "specs": {
          "weight": "850g",
          "waterResistance": "Déperlante",
          "warmthRating": "Très élevée",
          "fitType": "Ajustée",
          "origin": "Atelier Pyrénées, France",
          "care": "Lavage délicat à la main ou nettoyage à sec"
        },
        "hotspots": [],
        "id": "produit-1787241378430-715p3s",
        "availabilityStatus": "on-sale",
        "customSpecs": {}
      },
      {
        "name": "Todebag",
        "subTitle": "Confection Artisanale des Pyrénées",
        "category": "Homme \u0026 Femme",
        "price": 50,
        "currency": "€",
        "heroImage": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787315218449-ChatGPT-Image-21-ao--t-2026--14_26_45.webp",
        "gallery": [
          "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787315218449-ChatGPT-Image-21-ao--t-2026--14_26_45.webp",
          "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787315239178-20260816_124113.jpg"
        ],
        "description": "Veste artisanale d'exception tissée dans les Pyrénées.",
        "longDescription": "Fabriquée selon des savoir-faire d'autrefois en pure laine sélectionnée.",
        "tagline": "L'élégance des cimes",
        "fabrics": [
          "Laine des Pyrénées 100% naturelle"
        ],
        "colors": [
          {
            "name": "Gris Aspe",
            "hex": "#4a524b"
          },
          {
            "name": "Ocre Vignemale",
            "hex": "#8c6b43"
          }
        ],
        "sizes": [
          "Taille unique"
        ],
        "isAvailable": true,
        "features": [
          {
            "iconName": "Shield",
            "title": "Coupe-Vent",
            "desc": "Protection thermique haute montagne"
          }
        ],
        "specs": {
          "weight": "850g",
          "waterResistance": "Déperlante",
          "warmthRating": "Très élevée",
          "fitType": "Ajustée",
          "origin": "Atelier Pyrénées, France",
          "care": "Lavage délicat à la main ou nettoyage à sec"
        },
        "hotspots": [
          {
            "id": "hotspot-1787252504808",
            "title": "Nouveau point tet",
            "description": "sdssdsds",
            "x": 48,
            "y": 32,
            "category": "fabric"
          }
        ],
        "id": "produit-1787242939553-ezbmjg",
        "availabilityStatus": "on-sale",
        "customSpecs": {}
      },
      {
        "name": "test",
        "subTitle": "Confection Artisanale des Pyrénées",
        "category": "Homme \u0026 Femme",
        "price": 490,
        "currency": "€",
        "heroImage": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format\u0026fit=crop\u0026q=80\u0026w=1000",
        "gallery": [
          "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format\u0026fit=crop\u0026q=80\u0026w=1000"
        ],
        "description": "Veste artisanale d'exception tissée dans les Pyrénées.",
        "longDescription": "Fabriquée selon des savoir-faire d'autrefois en pure laine sélectionnée.",
        "tagline": "L'élégance des cimes",
        "fabrics": [
          "Laine des Pyrénées 100% naturelle"
        ],
        "colors": [
          {
            "name": "Gris Aspe",
            "hex": "#4a524b"
          },
          {
            "name": "Ocre Vignemale",
            "hex": "#8c6b43"
          }
        ],
        "sizes": [
          "S",
          "M",
          "L",
          "XL",
          "test"
        ],
        "isAvailable": false,
        "availabilityStatus": "sold-out",
        "features": [
          {
            "iconName": "Shield",
            "title": "Coupe-Vent",
            "desc": "Protection thermique haute montagne"
          }
        ],
        "specs": {
          "weight": "850g",
          "waterResistance": "Déperlante",
          "warmthRating": "Très élevée",
          "fitType": "Ajustée",
          "origin": "Atelier Pyrénées, France",
          "care": "Lavage délicat à la main ou nettoyage à sec"
        },
        "hotspots": [],
        "customSpecs": {},
        "id": "produit-1787294817714-0t3rcd"
      }
    ],
    "theme": {
      "buttonStyle": "gold-laiton",
      "buttonRadius": "rounded-full",
      "buttonSize": "standard",
      "buttonBackgroundImageUrl": "",
      "buttonBackgroundOverlay": 28,
      "buttonOverrides": {
        "navbar-order": {
          "buttonStyle": "cuir-naturel",
          "buttonSize": "compact",
          "buttonRadius": "rounded-full",
          "backgroundImageUrl": "",
          "backgroundOverlay": 41,
          "buttonTextSize": "small",
          "buttonTextColor": ""
        },
        "hero-discover": {
          "buttonSize": "standard",
          "buttonStyle": "gold-laiton",
          "backgroundOverlay": 26,
          "buttonRadius": "rounded-none"
        },
        "hero-order": {
          "buttonStyle": "gold-laiton",
          "backgroundImageUrl": "/assets/persistent-media-1.png"
        },
        "showcase-order": {
          "buttonStyle": "gold-laiton"
        },
        "lookbook-order": {
          "buttonStyle": "gold-laiton",
          "buttonTextColor": ""
        },
        "comparison-order": {
          "buttonStyle": "gold-laiton"
        },
        "footer-workshop": {
          "buttonStyle": "sapin-cimes"
        }
      },
      "cardStyle": "atelier-relief",
      "heroLayout": "split-cards",
      "showcaseLayout": "split-interactive",
      "sectionOrder": [
        "hero",
        "collection",
        "comparatif",
        "lookbook",
        "origines",
        "contact"
      ],
      "hiddenSections": [],
      "textAlign": "center",
      "buttonAlign": "center",
      "heroBadgePosition": "top",
      "cardMediaPosition": "left",
      "contentPadding": "comfortable",
      "containerWidth": "standard",
      "showcaseImageScale": 100,
      "showcaseImageFrameWidth": 70,
      "showcaseImageFrameHeight": 360,
      "lookbookImageScale": 100,
      "lookbookImageFrameWidth": 60,
      "lookbookImageFrameHeight": 220,
      "sectionBackgroundImages": {
        "origines": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787258626442-4k-wallpaper-blue-skies-conifers-1526720.webp",
        "hero": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787315389264-ChatGPT-Image-21-ao--t-2026--14_28_34.png"
      },
      "sectionBackgroundMedia": {
        "hero": {
          "type": "image",
          "url": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787315389264-ChatGPT-Image-21-ao--t-2026--14_28_34.png",
          "overlay": 0,
          "objectFit": "cover",
          "positionX": 50,
          "positionY": 50
        }
      },
      "siteThemePreset": "pyrenees-noir",
      "siteBackgroundColor": "#121613",
      "navBackgroundColor": "#1a1e1b",
      "navBackgroundOpacity": 25,
      "sectionBackgroundOpacity": {
        "hero": 85,
        "collection": 75,
        "origines": 45
      },
      "sectionWidthPercent": {
        "collection": 110
      },
      "lookbookProductIds": [],
      "productBlocksOrder": [
        "title-price",
        "colors",
        "sizes",
        "cta",
        "specs",
        "description"
      ],
      "formFieldsOrder": [
        "name",
        "email",
        "phone",
        "jacket",
        "color",
        "size",
        "requestType",
        "message"
      ],
      "orderButtonText": "Commander",
      "discoverButtonText": "Découvrir",
      "inquiryButtonText": "Commander sur Mesure",
      "workshopButtonText": "Prendre Rendez-vous à l'Atelier",
      "heroBadgeText": "Édition Limitée des Pyrénées",
      "heroTitlePrefix": "Maison Mailhagut",
      "landingBoutiqueKicker": "MAISON MAILHAGUT",
      "landingBoutiqueTitle": "La Boutique",
      "landingGiteKicker": "PYRÉNÉES",
      "landingGiteTitle": "Le Gîte",
      "comparisonCriteria": [
        {
          "id": "crit_category",
          "label": "Style principal",
          "key": "category"
        },
        {
          "id": "crit_fabric",
          "label": "Tissu signature",
          "key": "fabric"
        },
        {
          "id": "crit_warmth",
          "label": "Indice de Chaleur",
          "key": "warmth"
        },
        {
          "id": "crit_water",
          "label": "Résistance à la pluie",
          "key": "water"
        },
        {
          "id": "crit_weight",
          "label": "Poids de la veste",
          "key": "weight"
        },
        {
          "id": "crit_fit",
          "label": "Coupe \u0026 Silhouette",
          "key": "fit"
        },
        {
          "id": "crit_care",
          "label": "Entretien",
          "key": "care"
        },
        {
          "id": "crit_1787242525693",
          "label": "test",
          "key": "custom_1787242525693"
        }
      ],
      "collectionTabLabel": "Les Articles",
      "navOrder": [
        "collection",
        "comparatif",
        "lookbook",
        "origines",
        "contact"
      ],
      "comparatifTabLabel": "Tableau Comparatif des Articles",
      "lookbookTabLabel": "Bibliothèque"
    },
    "logos": {
      "boutique": {
        "imageUrl": "https://fw3pw0zady2vfqcl.public.blob.vercel-storage.com/site-media/1787254609604-Logo.png",
        "text": "Maison Mailhagut",
        "secondaryText": "Au coeur des pyrénées",
        "fontFamily": "serif",
        "textColor": "#b38144",
        "textSize": "21px",
        "imageSize": 58,
        "gap": 12,
        "showText": true
      },
      "gite": {
        "imageUrl": "/assets/persistent-media-2.png",
        "text": "GÎTE DES\nPYRER",
        "secondaryText": "Un espace de détente",
        "fontFamily": "sans",
        "textColor": "#f3ece0",
        "textSize": "20px",
        "imageSize": 58,
        "gap": 12,
        "showText": true
      }
    }
  },
  "editorConfig": {
    "adminBarPosition": "bottom",
    "floatingImages": [],
    "schemaVersion": 5,
    "blocks": [
      {
        "id": "block-1787003030958",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 55,
        "text": "Nouveau textetest",
        "visible": true,
        "kind": "text"
      },
      {
        "id": "element-bgfo10",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Nouveau texte",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e div.fixed.z-\\[25\\]:nth-of-type(2) \u003e div.px-3.py-2",
        "kind": "text",
        "fontFamily": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", \"Noto Sans\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
        "fontSize": "16px",
        "color": "#f3ece0"
      },
      {
        "id": "element-2j3eoa",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Édition Limitée des Pyrénées",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.flex.justify-center:nth-of-type(1) \u003e div.inline-flex.items-center \u003e span.text-\\[\\#e2d5c3\\]:nth-of-type(3)",
        "kind": "text",
        "fontFamily": "ui-serif, Georgia, Cambria, \"Times New Roman\", Times, serif",
        "fontSize": "12px",
        "color": "#f0f0f0"
      },
      {
        "id": "element-7hx1tr",
        "type": "heading",
        "section": "hero",
        "x": 50,
        "y": 50,
        "text": "Thème Champêtre \u0026 Élégance  \nMAISON Mailha",
        "visible": true,
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.text-center.max-w-4xl:nth-of-type(2) \u003e h1.font-serif.text-4xl",
        "kind": "text",
        "fontFamily": "Playfair Display, Georgia, serif",
        "fontSize": "64px",
        "color": "#a98334"
      },
      {
        "id": "element-1yp1kl6",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-role=\"hero-line-2\"]",
        "kind": "text",
        "text": "MAISON MAILHAG",
        "fontFamily": "ui-serif",
        "fontSize": "72px",
        "color": "rgb(245, 238, 223)"
      },
      {
        "id": "element-y3kce5",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(1) \u003e h3:nth-of-type(1)",
        "kind": "text",
        "text": "MAISON MAILHA",
        "fontFamily": "ui-serif",
        "fontSize": "20px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-1pm4g7c",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(1)",
        "kind": "text",
        "text": "3. Tableau Comparatif",
        "fontFamily": "ui-serif",
        "fontSize": "12px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-1f5ergz",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "div:nth-of-type(3) \u003e section:nth-of-type(1) \u003e div:nth-of-type(2) \u003e div:nth-of-type(1) \u003e h2:nth-of-type(1)",
        "kind": "text",
        "text": "Tableau des articles",
        "fontFamily": "ui-serif",
        "fontSize": "48px",
        "color": "rgb(243, 236, 224)"
      },
      {
        "id": "element-115krkx",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-hero-line=\"2\"]",
        "kind": "text",
        "text": "Thème Champêtre \u0026 Élégance",
        "fontFamily": "ui-serif",
        "fontSize": "60px",
        "color": "rgb(245, 238, 223)",
        "locator": {
          "tag": "span",
          "text": "MAISON Mailhag 4",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "element-1dd70g4",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "button:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(2)",
        "kind": "text",
        "text": "Édition Limitée des Pyrénées",
        "fontFamily": "-apple-system",
        "fontSize": "10px",
        "color": "#d2b16f"
      },
      {
        "id": "element-1oie024",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "kind": "text",
        "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
        "fontFamily": "-apple-system",
        "fontSize": "16px",
        "color": "rgb(163, 176, 162)",
        "locator": {
          "tag": "p",
          "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 4.",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "element-1ju1s8k",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "selector": "[data-vce-hero-line=\"1\"]",
        "kind": "text",
        "text": "Maison Mailhagut",
        "fontFamily": "ui-serif",
        "fontSize": "72px",
        "color": "rgb(194, 162, 109)",
        "locator": {
          "tag": "span",
          "text": "Thème Champêtre \u0026 Élégance 4",
          "sectionId": "hero",
          "occurrence": 0
        }
      },
      {
        "id": "hero-tagline",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "p",
          "text": "\"Élégance Champêtre \u0026 Artisanat des Cimes 5\"",
          "sectionId": "hero",
          "occurrence": 0
        },
        "kind": "text",
        "text": " -  Artisanat local  -",
        "fontFamily": "ui-serif",
        "fontSize": "24px",
        "color": "rgb(208, 197, 180)"
      },
      {
        "id": "hero-subtitle",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "p",
          "text": "Conçues au cœur de la chaîne pyrénéenne, deux vestes d’exception mariant matières nobles et coupe haute couture 1.",
          "sectionId": "hero",
          "occurrence": 0
        },
        "kind": "text",
        "text": "Conçues au cœur de la chaîne pyrénéenne, des articles d’exception mariant matières nobles et la laine de nos brebis.",
        "fontFamily": "-apple-system",
        "fontSize": "16px",
        "color": "rgb(163, 176, 162)"
      },
      {
        "id": "hero-designer-location",
        "type": "text",
        "section": "hero",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "span",
          "text": "Vallée de Lourdios \u0026 Pic du Midi",
          "sectionId": "hero",
          "occurrence": 0
        },
        "kind": "text",
        "text": "ILHET - Vallée d'Aure",
        "fontFamily": "ui-serif",
        "fontSize": "12px",
        "color": "rgb(212, 175, 55)"
      },
      {
        "id": "story-designer-location",
        "type": "text",
        "section": "origines",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "p",
          "text": "Vallée de Lourdios \u0026 Pic du Midi",
          "sectionId": "origines",
          "occurrence": 0
        },
        "kind": "text",
        "text": "ILHET - Vallée d'Aure",
        "fontFamily": "-apple-system",
        "fontSize": "12px",
        "color": "rgb(163, 177, 165)"
      },
      {
        "id": "vce-ardxk5",
        "type": "text",
        "section": "origines",
        "x": 50,
        "y": 50,
        "visible": true,
        "locator": {
          "tag": "blockquote",
          "text": "\"Élégance Champêtre \u0026 Artisanat des Cimes 5\"",
          "sectionId": "origines",
          "occurrence": 0
        },
        "kind": "text",
        "text": "- Artisanat local -",
        "fontFamily": "ui-serif",
        "fontSize": "14px",
        "color": "rgb(208, 197, 180)"
      }
    ],
    "editorElements": {
      "block-1787003030958": {
        "id": "block-1787003030958",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "element-bgfo10": {
        "id": "element-bgfo10",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e div.fixed.z-\\[25\\]:nth-of-type(2) \u003e div.px-3.py-2",
        "locator": "data-vce-id"
      },
      "element-2j3eoa": {
        "id": "element-2j3eoa",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.flex.justify-center:nth-of-type(1) \u003e div.inline-flex.items-center \u003e span.text-\\[\\#e2d5c3\\]:nth-of-type(3)",
        "locator": "data-vce-id"
      },
      "element-7hx1tr": {
        "id": "element-7hx1tr",
        "type": "heading",
        "kind": "text",
        "section": "hero",
        "selector": "div \u003e div.min-h-screen.bg-\\[\\#121613\\] \u003e main \u003e div.relative.transition-all:nth-of-type(1) \u003e section.relative.min-h-screen \u003e div.relative.z-10:nth-of-type(3) \u003e div.text-center.max-w-4xl:nth-of-type(2) \u003e h1.font-serif.text-4xl",
        "locator": "data-vce-id"
      },
      "element-1yp1kl6": {
        "id": "element-1yp1kl6",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-role=\"hero-line-2\"]",
        "locator": "data-vce-id"
      },
      "element-y3kce5": {
        "id": "element-y3kce5",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(1) \u003e h3:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-1pm4g7c": {
        "id": "element-1pm4g7c",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(1) \u003e div:nth-of-type(3) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-1f5ergz": {
        "id": "element-1f5ergz",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "div:nth-of-type(3) \u003e section:nth-of-type(1) \u003e div:nth-of-type(2) \u003e div:nth-of-type(1) \u003e h2:nth-of-type(1)",
        "locator": "data-vce-id"
      },
      "element-115krkx": {
        "id": "element-115krkx",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-hero-line=\"2\"]",
        "locator": "data-vce-id"
      },
      "element-1dd70g4": {
        "id": "element-1dd70g4",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "button:nth-of-type(1) \u003e div:nth-of-type(1) \u003e span:nth-of-type(2)",
        "locator": "data-vce-id"
      },
      "element-1oie024": {
        "id": "element-1oie024",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "element-1ju1s8k": {
        "id": "element-1ju1s8k",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": "[data-vce-hero-line=\"1\"]",
        "locator": "data-vce-id"
      },
      "hero-tagline": {
        "id": "hero-tagline",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "hero-subtitle": {
        "id": "hero-subtitle",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "hero-designer-location": {
        "id": "hero-designer-location",
        "type": "text",
        "kind": "text",
        "section": "hero",
        "selector": null,
        "locator": "data-vce-id"
      },
      "story-designer-location": {
        "id": "story-designer-location",
        "type": "text",
        "kind": "text",
        "section": "origines",
        "selector": null,
        "locator": "data-vce-id"
      },
      "vce-ardxk5": {
        "id": "vce-ardxk5",
        "type": "text",
        "kind": "text",
        "section": "origines",
        "selector": null,
        "locator": "data-vce-id"
      }
    }
  },
  "publishedAt": 1787319303332
} as const;
