import type { VercelRequest, VercelResponse } from '@vercel/node';
import { getRedisClient, parseCookies, verifySessionToken } from './_helpers.js';

const REDIS_KEY = 'mdp_site_config';
const REVISION_KEY = 'mdp_site_revision';

function safeJson(value: unknown) {
  return JSON.stringify(value, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

function generatedFile(config: any, revision: number) {
  const brandData = config?.brandData ?? {};
  const editorConfig = config?.editorConfig ?? {};

  return `// AUTO-GENERATED BY THE SITE VISUAL EDITOR.
// Do not edit manually: the next publication will overwrite this file.

export const publishedSiteContent = ${safeJson({
    publishedRevision: revision,
    brandData,
    editorConfig,
  })} as const;
`;
}

function extractRevision(content: string): number {
  const match = content.match(
    /"publishedRevision"\\s*:\\s*(\\d+)/
  );

  if (!match) return 0;

  const value = Number(match[1]);
  return Number.isFinite(value) ? value : 0;
}

function stripRevision(content: string): string {
  return content.replace(
    /"publishedRevision"\\s*:\\s*\\d+\\s*,?/,
    ''
  );
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'PUT') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed',
    });
  }

  const session = verifySessionToken(
    parseCookies(req.headers.cookie).admin_session
  );

  if (!session.valid) {
    return res.status(401).json({
      success: false,
      error: 'Non autorisé',
    });
  }

  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;
  const branch = process.env.GITHUB_BRANCH || 'main';
  const filePath =
    process.env.GITHUB_PUBLISHED_FILE ||
    'src/data/site-content.generated.ts';

  if (!token || !repository) {
    return res.status(503).json({
      success: false,
      error: 'GITHUB_TOKEN ou GITHUB_REPOSITORY manque dans Vercel.',
    });
  }

  const body =
    typeof req.body === 'string'
      ? JSON.parse(req.body)
      : req.body;

  const config = body?.config;

  if (!config || typeof config !== 'object') {
    return res.status(400).json({
      success: false,
      error: 'config est obligatoire.',
    });
  }

  const [owner, repo] = repository.split('/');

  if (!owner || !repo) {
    return res.status(500).json({
      success: false,
      error: 'GITHUB_REPOSITORY doit être owner/repository.',
    });
  }

  const apiUrl =
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;

  const headers = {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent': 'Site-Internet-Benoit-V61',
  };

  try {
    const readCurrent = async () => {
      const existing = await fetch(
        `${apiUrl}?ref=${encodeURIComponent(branch)}`,
        { headers }
      );

      if (existing.ok) return await existing.json();

      if (existing.status === 404) return null;

      const text = await existing.text();

      throw new Error(
        `Lecture GitHub impossible (${existing.status}): ${text.slice(0, 300)}`
      );
    };

    let existingData = await readCurrent();

    let currentContent = '';
    let commitSha: string | null = null;

    if (existingData?.content) {
      try {
        currentContent = Buffer.from(
          String(existingData.content).replace(/\\s+/g, ''),
          'base64'
        ).toString('utf8');
      } catch {
        currentContent = '';
      }
    }

    const currentRevision = extractRevision(currentContent);

    /*
     * Chaque publication reçoit une révision monotone.
     * Upstash conserve cette révision avec la configuration.
     * Le navigateur pourra ainsi refuser une configuration serveur
     * plus ancienne que celle déjà embarquée dans le bundle Vercel.
     */
    let revision = Date.now();

    const redis = getRedisClient();

    if (redis) {
      try {
        const counter = await redis.incr(REVISION_KEY);

        if (
          Number.isFinite(Number(counter)) &&
          Number(counter) > revision
        ) {
          revision = Number(counter);
        }

        if (revision <= currentRevision) {
          revision = currentRevision + 1;
        }

        // Le compteur doit rester au moins au niveau de la révision publiée.
        await redis.set(REVISION_KEY, revision);
      } catch (error) {
        console.warn(
          'Impossible de générer la révision Upstash, fallback timestamp:',
          error
        );

        revision = Math.max(Date.now(), currentRevision + 1);
      }
    } else {
      revision = Math.max(Date.now(), currentRevision + 1);
    }

    const content = generatedFile(config, revision);
    const encoded = Buffer.from(content, 'utf8').toString('base64');

    // Si le contenu fonctionnel est identique, ne crée pas de nouveau commit.
    // On garde cependant la révision déjà publiée.
    if (
      currentContent &&
      stripRevision(currentContent) === stripRevision(content)
    ) {
      revision = currentRevision || revision;
    } else {
      const updateOnce = async (sha?: string) => {
        const payload: Record<string, unknown> = {
          message: 'chore(site-editor): publish visual site changes',
          content: Buffer.from(
            generatedFile(config, revision),
            'utf8'
          ).toString('base64'),
          branch,
        };

        if (sha) payload.sha = sha;

        return fetch(apiUrl, {
          method: 'PUT',
          headers,
          body: JSON.stringify(payload),
        });
      };

      let update = await updateOnce(existingData?.sha);

      // Une autre publication peut avoir changé le SHA entre la lecture
      // et l'écriture. On relit une fois et on repart avec le dernier SHA.
      if (update.status === 409) {
        existingData = await readCurrent();
        update = await updateOnce(existingData?.sha);
      }

      const result = await update.json().catch(() => ({}));

      if (!update.ok) {
        return res.status(502).json({
          success: false,
          error:
            result?.message ||
            `GitHub a refusé la publication (${update.status}).`,
        });
      }

      commitSha = result?.commit?.sha || null;
    }

    /*
     * IMPORTANT :
     * GitHub + Upstash sont mis à jour par UNE SEULE route.
     * App.tsx ne fait donc plus un PUT séparé vers /api/site-config.
     * Cela évite le scénario où GitHub reçoit A puis Upstash reçoit
     * accidentellement B/A dans un ordre différent.
     */
    if (redis) {
      try {
        await redis.set(REDIS_KEY, {
          config,
          revision,
        });
      } catch (error) {
        console.error(
          'GitHub publié mais synchronisation Upstash impossible:',
          error
        );

        return res.status(200).json({
          success: true,
          warning:
            'Publication GitHub réussie, mais Upstash n’a pas pu être synchronisé.',
          commitSha,
          revision,
          path: filePath,
          branch,
        });
      }
    }

    return res.status(200).json({
      success: true,
      commitSha,
      revision,
      path: filePath,
      branch,
    });
  } catch (error) {
    console.error('site-publish:', error);

    return res.status(500).json({
      success: false,
      error: 'Erreur pendant la publication GitHub.',
    });
  }
}
