import type { VercelRequest, VercelResponse } from '@vercel/node';

function getAdminSecret(req: VercelRequest) {
  const cookie = req.headers.cookie || '';
  const match = cookie.match(/(?:^|;\s*)admin_session=([^;]+)/);
  return match ? decodeURIComponent(match[1]) : '';
}

function safeJson(value: unknown) {
  return JSON.stringify(value, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

function generatedFile(config: any) {
  const brandData = config?.brandData ?? {};
  const editorConfig = config?.editorConfig ?? {};
  return `// AUTO-GENERATED BY THE SITE VISUAL EDITOR.
// Do not edit manually: the next publication will overwrite this file.

export const publishedSiteContent = ${safeJson({
    brandData,
    editorConfig,
  })} as const;
`;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'PUT') {
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  }

  // The same admin cookie used by the existing admin API is required.
  // If your project uses a different cookie name, change ADMIN_SESSION_COOKIE.
  const configuredSecret = process.env.ADMIN_SECRET || '';
  const session = getAdminSecret(req);

  if (configuredSecret && session !== configuredSecret) {
    return res.status(401).json({ success: false, error: 'Non autorisé' });
  }

  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;
  const branch = process.env.GITHUB_BRANCH || 'main';
  const filePath =
    process.env.GITHUB_PUBLISHED_FILE ||
    'src/data/site-content.generated.ts';

  if (!token || !repository) {
    return res.status(503).json({
      success: false,
      error: 'GITHUB_TOKEN ou GITHUB_REPOSITORY manque dans Vercel.',
    });
  }

  const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  const config = body?.config;

  if (!config || typeof config !== 'object') {
    return res.status(400).json({
      success: false,
      error: 'config est obligatoire.',
    });
  }

  const [owner, repo] = repository.split('/');
  if (!owner || !repo) {
    return res.status(500).json({
      success: false,
      error: 'GITHUB_REPOSITORY doit être owner/repository.',
    });
  }

  const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;

  const headers = {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent': 'Site-Internet-Benoit-V14',
  };

  try {
    let sha: string | undefined;

    const existing = await fetch(`${apiUrl}?ref=${encodeURIComponent(branch)}`, {
      headers,
    });

    if (existing.ok) {
      const data = await existing.json();
      sha = data.sha;
    } else if (existing.status !== 404) {
      const text = await existing.text();
      return res.status(502).json({
        success: false,
        error: `Lecture GitHub impossible (${existing.status}): ${text.slice(0, 300)}`,
      });
    }

    const content = generatedFile(config);
    const encoded = Buffer.from(content, 'utf8').toString('base64');

    const payload: Record<string, unknown> = {
      message: 'chore(site-editor): publish visual site changes',
      content: encoded,
      branch,
    };

    if (sha) payload.sha = sha;

    const update = await fetch(apiUrl, {
      method: 'PUT',
      headers,
      body: JSON.stringify(payload),
    });

    const result = await update.json().catch(() => ({}));

    if (!update.ok) {
      return res.status(502).json({
        success: false,
        error:
          result?.message ||
          `GitHub a refusé la publication (${update.status}).`,
      });
    }

    return res.status(200).json({
      success: true,
      commitSha: result?.commit?.sha || null,
      path: filePath,
      branch,
    });
  } catch (error) {
    console.error('site-publish:', error);
    return res.status(500).json({
      success: false,
      error: 'Erreur pendant la publication GitHub.',
    });
  }
}
